### PR TITLE
Tooltips and minor fixes in UI

### LINKED ISSUE #107: Add tooltips
Add tooltips on buttons:
- [x] Settings
- [x] Refresh
- [x] Delete (on note)
- [x] Edit (on note)

Also, we should improve accessibility.

### PR DESCRIPTION
**Pull request by swouf**
In this PR, I also changed the action buttons in the notes to be square and removed the disabling of the _reset view_ button.

close #107

### CODE REVIEW

File: src/components/main/note/Note.tsx [hunk 1]
```diff
@@ -45,6 +46,7 @@ const SmallActionButton = styled(IconButton)(() => ({
   borderRadius: '50%',
   position: 'absolute',
   scale: [0.5, 0.5, 1],
+  fontSize: '0rem', // Ensures button remains square.
```
Comment (spaenleh) [inline src/components/main/note/Note.tsx:49]: Interesting ! I used `span`s to wrap elements and keep them square. If this works too then 🆗 !

**Review by spaenleh — APPROVED** [review]
Looks good to me !

File: src/components/main/note/Note.tsx (hunk 1 above)
Comment (swouf) [reply src/components/main/note/Note.tsx:49]: In my case, `span` did not work, thus I fixed the font size to 0. Works perfectly 💯
